### ISSUE TITLE
problem with subscriber and channel lists

### ISSUE THREAD

**Issue by MazumdarAyush07** [shaam001/chai-backend#1]
In the subscription controller, getSubscribers and getSubscribedChannels functions are not able to accept the values from params and the respective values are showing undefined

**Comment by shaam001** [comment]
I think the code is working fine. Please check if you are logged in or not, and ensure that you are hitting the API like this: http://localhost:8000/api/v1/subscriptions/c/channelId for getUserChannelSubscribers, and for getSubscribedChannels: http://localhost:8000/api/v1/subscriptions/u/subscriberId

**Comment by shaam001** [comment]
I think the code is working fine. Please check if you are logged in or not, and ensure that you are hitting the API like this: http://localhost:8000/api/v1/subscriptions/c/channelId for getUserChannelSubscribers, and for getSubscribedChannels: http://localhost:8000/api/v1/subscriptions/u/subscriberId
